William/handle conflicts
EdgeApp/edge-sync-client pull request #18
Opened 2024-02-19 18:53 UTC by swansontec

### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [x] Yes
- [ ] No

### Dependencies

 none

### Description

 none

2024-02-19 23:00 UTC, samholmes requested changes
Very clean; very good PR! I only have some questions before approving.

2024-02-19 23:00 UTC, samholmes commented on src/types/rest-types.ts
> + * @file The types in this file describe the sync-server's REST protocol.
`@file`?

2024-02-19 23:00 UTC, samholmes commented on src/types/rest-types.ts
> + * - FooResponse: The JSON response body the endpoint returns.
What are these `Foo` things? Maybe you mean to describe the pattern between each cleaner exported; Is there a better way to explain that in this comment?

2024-02-19 23:00 UTC, samholmes commented on src/client/sync-client.ts
> -  params?: ApiRequestParams
It's been a while since looking at this implementation. Why wasn't this ever used, I wonder.

2024-02-19 23:00 UTC, samholmes commented on src/client/sync-client.ts
> +  async function openResponse<T>(
Name suggestion `unpackResponse` or `validateResponse` might be better?

2024-02-19 23:00 UTC, samholmes commented on src/client/sync-client.ts
> +          body: JSON.stringify(wasPostStoreBody(body)),
This uncleaner was slipped into this commit without explanation. We we not uncleaning before. Are safe from regressions here? What's the motivation behind the change; is it just to do the correct thing by uncleaning before sending it off to the network?

2024-02-19 23:06 UTC, swansontec commented on src/types/rest-types.ts
> + * @file The types in this file describe the sync-server's REST protocol.
https://jsdoc.app/tags-file

2024-02-19 23:08 UTC, swansontec commented on src/client/sync-client.ts
> -  params?: ApiRequestParams
It is only used on the server side. On the client side you just bash the URL string together using template expressions.

2024-02-19 23:17 UTC, swansontec commented on src/client/sync-client.ts
> +          body: JSON.stringify(wasPostStoreBody(body)),
Cleaners can modify arbitrary data, such as converting strings to `Date` objects, parsing hex, and so forth. It is *never* safe to call `JSON.stringify` when cleaners are involved, since JSON doesn't know how to un-do these transformations, and the type system won't help track down the error. You just get data that won't round-trip, and you have to track the errors down by hand.

Fortunately, the `asPostStoreBody` cleaner doesn't do any data transformation, so this is a no-op for now. Things just just "happen to work" either way. I don't like code that "just happens to work", so I'm adding the safety now while I'm in there.

Unfortunately, the `asEdgeBox` cleaner in edge-sync-client doesn't match the version in edge-core-js, which parses base64 into a `Uint8Array`. If we ever bring the two into alignment, the uncleaner will become necessary to turn the `Uint8Array` back to base64.

2024-02-20 02:33 UTC, samholmes approved these changes

2024-02-20 02:34 UTC, samholmes commented on src/client/sync-client.ts
> -  params?: ApiRequestParams
This must have been some kind of mixup when I added it then.

2024-02-26 18:53 UTC, closed without merging